# Generated by Django 4.0.3 on 2022-03-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='User',
        ),
    ]
