# Generated by Django 4.0.3 on 2022-04-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_rename_user_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='User',
            new_name='user',
        ),
    ]
